name: dash
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  loading_indicator: ^2.0.1
  get: ^4.1.4
  dio: ^4.0.0
  top_snackbar_flutter: ^1.0.0
  get_storage: ^2.0.2
  dartz: ^0.10.0-nullsafety.2
  google_fonts: ^2.1.0
  flutter_typeahead: ^3.1.3
  flutter_svg: ^0.22.0
  date_time_picker: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  pdf: ^3.3.0
  path_provider: ^2.0.2
  open_file: ^3.2.1
  universal_html: ^2.0.8
  http: ^0.13.3
  http_client_helper: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
